### ISSUE TITLE
MacOS build in releases

### ISSUE THREAD

**Issue by MrRefactoring** [ozkanpakdil/big-file-editor#1]
Hi! Thanks for the app, it works exactly as intended.

But to start using it, I had to download the source files and compile them for macOS.
Could you also include the compiled macOS app in the release?

**Comment by ozkanpakdil** [comment]
Hi, happy to hear it works, I dont have a mac but here is a build release https://github.com/ozkanpakdil/big-file-editor/releases/tag/MacOs_2022.04.16_13-12 feel free to test :)

**Comment by ozkanpakdil** [comment]
I changed the release logic here is the latest one https://github.com/ozkanpakdil/big-file-editor/releases/tag/1.0.107 I think I will make linux too :)

**Comment by ozkanpakdil** [comment]
linux rpm and exe and all. https://github.com/ozkanpakdil/big-file-editor/releases/tag/1.0.133

**Comment by MrRefactoring** [comment]
Looks like it working :) 
Thank you!
<img width="1032" alt="Screenshot 2022-04-18 at 11 30 00" src="https://user-images.githubusercontent.com/10329528/163772977-28d3543c-c153-45cf-b6ed-1280e7876b0c.png">
